# Generated by Django 4.2.7 on 2023-11-17 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'tax', 'verbose_name_plural': 'taxes'},
        ),
    ]
