# Generated by Django 4.2.7 on 2023-11-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_tax_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='tax_slug',
            field=models.SlugField(blank=True, max_length=20, unique=True),
        ),
    ]
