# Generated by Django 4.2.7 on 2023-11-19 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordereditems',
            options={'verbose_name': 'ordereditems', 'verbose_name_plural': 'ordereditems'},
        ),
    ]
